language: go

dist: bionic

env:
  global:
    - CACHE_NAME=${TRAVIS_ARCH}
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - HUGO_BUILD_TAGS=extended

git:
  depth: false

go:
  - "1.13.4"

arch:
  - amd64

os:
  - linux

jobs:
  fast_finish: true

cache:
  directories:
    - $HOME/gopath/pkg/mod
    - $HOME/.cache/go-build
    - $HOME/Library/Caches/go-build
    - $HOME/AppData/Local/go-build

before_install:
  - df -h
    # https://travis-ci.community/t/go-cant-find-gcc-with-go1-11-1-on-windows/293/5
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        choco install mingw -y;
        export PATH=/c/tools/mingw64/bin:"$PATH";
    fi
  - gem install asciidoctor
  - type asciidoctor

install:
  - mkdir -p $HOME/src
  - mv $TRAVIS_BUILD_DIR $HOME/src
  - export TRAVIS_BUILD_DIR=$HOME/src/hugo
  - cd $HOME/src/hugo
  - go get github.com/magefile/mage

script:
  - go mod tidy
  - df -h
  - export HUGO_BUILD_TAGS=extended
  - mage -v docker
  - docker tag hugo kaleocheng/hugo
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
  - docker push kaleocheng/hugo

services:
  - docker
